### ISSUE TITLE
README instructions not working

### ISSUE THREAD

**Issue by csdlee** [huntlabs/hunt-framework#117]
Error: module `bootstrap` is in file 'bootstrap.d' which cannot be read

Performing "debug" build using /usr/bin/dmd for x86_64.
dredis 0.0.9: target for configuration "library" is up to date.
hunt 1.0.0-rc.5: target for configuration "library" is up to date.
hunt-cache 0.2.1: target for configuration "default" is up to date.
hunt-sql 1.0.1: target for configuration "library" is up to date.
hunt-database 1.0.2: target for configuration "default" is up to date.
hunt-entity 2.0.4: target for configuration "empty" is up to date.
hunt-security 0.0.4: target for configuration "library" is up to date.
hunt-net 0.0.9: target for configuration "default" is up to date.
hunt-http 0.0.10: target for configuration "default" is up to date.
hunt-stomp 0.0.1-beta.1: target for configuration "library" is up to date.
hunt-framework 2.0.0-beta.4: target for configuration "lite" is up to date.
hunt-skeleton 1.0.0+commit.5.ga409f3c: building configuration "application"...
Error: module `bootstrap` is in file 'bootstrap.d' which cannot be read
import path[0] = source/
import path[1] = ../../.dub/packages/hunt-framework-2.0.0-beta.4/hunt-framework/source/
import path[2] = ../../.dub/packages/hunt-cache-0.2.1/hunt-cache/source/
import path[3] = ../../.dub/packages/dredis-0.0.9/dredis/source/
import path[4] = ../../.dub/packages/hunt-1.0.0-rc.5/hunt/source/
import path[5] = ../../.dub/packages/hunt-entity-2.0.4/hunt-entity/source/
import path[6] = ../../.dub/packages/hunt-database-1.0.2/hunt-database/source/
import path[7] = ../../.dub/packages/hunt-sql-1.0.1/hunt-sql/source/
import path[8] = ../../.dub/packages/hunt-http-0.0.10/hunt-http/source/
import path[9] = ../../.dub/packages/hunt-net-0.0.9/hunt-net/source/
import path[10] = ../../.dub/packages/hunt-security-0.0.4/hunt-security/source/
import path[11] = ../../.dub/packages/hunt-stomp-0.0.1-beta.1/hunt-stomp/source/
import path[12] = /usr/include/dmd/phobos
import path[13] = /usr/include/dmd/druntime/import
/usr/bin/dmd failed with exit code 1.

dmd 2.083

**Comment by zoujiaqing** [comment]
This question about dlang's compiler or dub, please waiting for response.

You can remove hunt-skeletion project's dub.json, remove line 12 to continue:
```json
 "mainSourceFile": "bootstrap.d",
```
or

```sh
dub run -v
```

**Comment by csdlee** [comment]
@zoujiaqing Thank you!
