### ISSUE TITLE
Support the new i18n function for View.

### ISSUE THREAD

**Issue by zoujiaqing** [huntlabs/hunt-framework#120]
@gaoxincheng 

resources/translations/en-us/messages.ini
```ini
HELLO_USER=Hello, %s , your id is: %d.
```

resources/translations/zh-cn/messages.ini
```ini
HELLO_USER=你好， %s ，你的ID是： %d。
```

```twig
{{ trans("HELLO_USER", username, userid) }}
```

**Comment by Heromyth** [comment]
See: https://github.com/huntlabs/hunt-examples/blob/master/website-basic/views/default/home.dhtml#L91
