### ISSUE TITLE
Creating a new Hunt project: dub init helloworld --type=hunt

### ISSUE THREAD

**Issue by BoQsc** [huntlabs/hunt-framework#130]
Something is not working, I tried to create a new project via `dub init helloworld --type=hunt`

And this is what I've got (instead of a well configured basic hunt project):

```
C:\Users\Juozas\Desktop\Naujas aplankas>dub init helloworld2 --type=hunt
hunt is not present, getting and storing it user wide
Fetching hunt 1.2.0...
Sub package "hunt:init-exec" doesn't exist.
```

However it still created these two files: 

- dub.json 
- .gitignore

And nothing more

**Comment by Heromyth** [comment]
We are not sure how works the dub. The Hunt 1.2.0 is always there: https://github.com/huntlabs/hunt/releases.

Maybe, you can have a try like these:
1) dub init -n
2) edit dub.json, and add the dependencies for hunt or hunt-framework mannually. See https://github.com/huntlabs/hunt-skeleton/blob/master/dub.json

**Comment by BoQsc** [comment]
@Heromyth If you ever be in the mood of doing anything with dub, check the referencing issue above. 😁

**Comment by andre2007** [comment]
With recent dub version all dub packages can influence the result of dub init. @BoQsc was trying to use this functionality. See referenced issue for more info.
