### ISSUE TITLE
cannot compile hunt-skeleton.

### ISSUE THREAD

**Issue by aferust** [huntlabs/hunt-framework#138]
Here is the output I get using ldc 1.17, windows 10 64 bit:

Unwind edges out of a funclet pad must have the same unwind dest
  %136 = cleanuppad within none []
  cleanupret from %136 unwind to caller
  invoke x86_vectorcallcc void @"\01_D4hunt11concurrency6thread11LockSupportQn6unparkFZv"() #2 [ "funclet"(token %136) ]
          to label %147 unwind label %177, !dbg !1575
in function _D4hunt4pool4impl17GenericObjectPool__TQwTCQBp5redis5RedisQgZQBs6createMFZCQCvQCt12PooledObject__TQrTQChZQy
LLVM ERROR: Broken function found, compilation aborted!
FAIL ..\..\AppData\Local\dub\packages\hunt-redis-1.0.1\hunt-redis\.dub\build\library-debug-windows-x86_64-ldc_2087-C15D6F43C8AC72C32F918515C60822FB\ hunt-redis staticLibrary
D:\msys64\home\user\dlang\ldc2-1.17.0-windows-x64\bin\ldc2.exe failed with exit code 1.

**Comment by Heromyth** [comment]
We will have a look about this.

**Comment by aferust** [comment]
Thank you. And this is the output using ldc 1.19 (windows x64):
C:\Users\user\Desktop\myproject>dub run
Fetching hunt-database 2.0.1 (getting selected version)...
Fetching hunt 1.4.3 (getting selected version)...
Fetching hunt-framework 2.2.5 (getting selected version)...
Fetching hunt-net 0.4.5 (getting selected version)...
Fetching hunt-http 0.4.0 (getting selected version)...
Fetching hunt-cache 0.6.2 (getting selected version)...
Fetching hunt-redis 1.1.0 (getting selected version)...
Fetching hunt-entity 2.5.4 (getting selected version)...
Performing "debug" build using D:\msys64\home\user\dlang\ldc2-1.19.0-windows-x64\bin\ldc2.exe for x86_64.
hunt 1.4.3: building configuration "library"...
hunt-net 0.4.5: building configuration "default"...
hunt-pool 1.0.0-rc.6: building configuration "library"...
hunt-redis 1.1.0: building configuration "library"...
Unwind edges out of a funclet pad must have the same unwind dest
  %136 = cleanuppad within none []
  cleanupret from %136 unwind to caller
  invoke x86_vectorcallcc void @"\01_D4hunt11concurrency6thread11LockSupportQn6unparkFZv"() #2 [ "funclet"(token %136) ]
          to label %147 unwind label %177, !dbg !1575
in function _D4hunt4pool4impl17GenericObjectPool__TQwTCQBp5redis5RedisQgZQBs6createMFZCQCvQCt12PooledObject__TQrTQChZQy
LLVM ERROR: Broken function found, compilation aborted!
D:\msys64\home\user\dlang\ldc2-1.19.0-windows-x64\bin\ldc2.exe failed with exit code 1.

**Comment by Heromyth** [comment]
It works well on Linux with DMD and LDC2. It also works on Windows with DMD.
It fails with LDC2 on Windows. It seems there is a bug in LDC2 on Windows. See also: https://bugs.llvm.org/show_bug.cgi?id=26698.

More tests are needed.

**Comment by aferust** [comment]
I get a memory allocation error using the latest DMD:
Performing "debug" build using D:\msys64\home\user\dlang\dmd.2.089.1.windows\dmd2\windows\bin\dmd.exe for x86_64.
hunt 1.4.3: target for configuration "library" is up to date.
hunt-net 0.4.5: target for configuration "default" is up to date.
hunt-pool 1.0.0-rc.6: target for configuration "library" is up to date.
hunt-redis 1.1.0: target for configuration "library" is up to date.
hunt-cache 0.6.2: target for configuration "default" is up to date.
hunt-sql 1.3.0: building configuration "library"...
---
ERROR: This is a compiler bug.
Please report it via https://issues.dlang.org/enter_bug.cgi
with, preferably, a reduced, reproducible example and the information below.
DustMite (https://github.com/CyberShadow/DustMite/wiki) can help with the reduction.
---
DMD v2.089.1-dirty
predefs   WITH_HUNT_ENTITY Have_hunt_sql Have_hunt HAVE_IOCP WITH_HUNT_CACHE DigitalMars Windows CRuntime_Microsoft CppRuntime_Microsoft LittleEndian D_Version2 all D_SIMD D_InlineAsm_X86_64 X86_64 Win64 D_LP64 assert D_ModuleInfo D_Exceptions D_TypeInfo D_HardFloat
binary    D:\msys64\home\user\dlang\dmd.2.089.1.windows\dmd2\windows\bin\dmd.exe
version   v2.089.1-dirty
config    D:\msys64\home\user\dlang\dmd.2.089.1.windows\dmd2\windows\bin\sc.ini
DFLAGS    -ID:\msys64\home\user\dlang\dmd.2.089.1.windows\dmd2\windows\bin\..\..\src\phobos -ID:\msys64\home\user\dlang\dmd.2.089.1.windows\dmd2\windows\bin\..\..\src\druntime\import -L/OPT:NOICF
---

core.exception.OutOfMemoryError@src\core\exception.d(647): Memory allocation failed
----------------
0x0063839A in onOutOfMemoryError
0x00598637 in Mem at C:\Users\vagrant\clones\dmd\src\dmd\root\rmem.d(134)
0x005985B6 in Mem at C:\Users\vagrant\clones\dmd\src\dmd\root\rmem.d(99)
0x00591D91 in OutBuffer at C:\Users\vagrant\clones\dmd\src\dmd\root\outbuffer.d(76)
0x004F4E7E in void dmd.libmscoff.LibMSCoff.WriteLibToBuffer(dmd.root.outbuffer.OutBuffer*) at C:\Users\vagrant\clones\dmd\src\dmd\libmscoff.d(463)
0x004DD04C in void dmd.lib.Library.write() at C:\Users\vagrant\clones\dmd\src\dmd\lib.d(110)
0x004FB12A in int dmd.mars.tryMain(uint, const(char)**, ref dmd.globals.Param) at C:\Users\vagrant\clones\dmd\src\dmd\mars.d(706)
0x004FB96A in _Dmain at C:\Users\vagrant\clones\dmd\src\dmd\mars.d(921)
0x0063AC1F in void rt.dmain2._d_run_main2(char[][], uint, extern (C) int function(char[][])*).runAll().__lambda1()
0x0063AB99 in void rt.dmain2._d_run_main2(char[][], uint, extern (C) int function(char[][])*).runAll()
0x0063AA34 in _d_run_main2
0x00637686 in _d_run_main
0x004FB911 in main at C:\Users\vagrant\clones\dmd\src\dmd\mars.d(870)
0x0065C331 in mainCRTStartup
0x74C36359 in BaseThreadInitThunk
0x77427B74 in RtlGetAppContainerNamedObjectPath
0x77427B44 in RtlGetAppContainerNamedObjectPath
D:\msys64\home\user\dlang\dmd.2.089.1.windows\dmd2\windows\bin\dmd.exe failed with exit code 1.

**Comment by Heromyth** [comment]
Fixed a bug in hunt-pool about this in commit https://github.com/huntlabs/hunt-pool/commit/2703ad300b97008cb646445725416dd6f82aa9b8.  Run `dub upgrade` to upgrade the dependencies.

By the way, the building requires a big memory. So check your memory size is bigger than 4G.

**Comment by aferust** [comment]
Thank you!  After your fix it compiled and worked without any problem .
