### ISSUE TITLE
Initialize hunt application

### ISSUE THREAD

**Issue by VanKrock** [huntlabs/hunt-framework#152]
How to initialize hunt application without git clone?

Something like:
`dub appliction.d`

```
"dependencies": {
    "hunt-framework": "~0.9.0"
},
```

**Comment by Heromyth** [comment]
It's not easy. 
Maybe, we need a customized tool with some templates to generate it, or add a template to dub.

**Comment by zoujiaqing** [comment]
@VanKrock You have look this simple documentation to create your project :)
https://github.com/huntlabs/hunt-framework/wiki/Quick-Start
