### ISSUE TITLE
Application stops after some requests

### ISSUE THREAD

**Issue by ddcovery** [huntlabs/hunt-framework#161]
I'm running hunt-skeleton app
After first request, app stops:
```
$ ./hunt-skeleton 
2020-Aug-01 00:09:35.3466182 | 14015 | trace | registerAuthUserConfig.__lambda1 | [name: admin, role: ["superuser"], name: guest, role: ["guest"]] | ../../../.dub/packages/hunt-framework-3.2.0/hunt-framework/source/hunt/framework/provider/ConfigServiceProvider.d:113
2020-Aug-01 00:09:35.3466698 | 14015 | trace | registerAuthUserConfig.__lambda1 | [name: superuser, permissions: ["user:add", "user:del"], name: guest, permissions: ["user:query"]] | ../../../.dub/packages/hunt-framework-3.2.0/hunt-framework/source/hunt/framework/provider/ConfigServiceProvider.d:114
2020-Aug-01 00:09:35.3467618 | 14015 | warning | DatabaseServiceProvider.buildEntityManagerFactory | The database is disabled. | ../../../.dub/packages/hunt-framework-3.2.0/hunt-framework/source/hunt/framework/provider/DatabaseServiceProvider.d:53


 ___  ___     ___  ___     ________      _________   
|\  \|\  \   |\  \|\  \   |\   ___  \   |\___   ___\     Hunt Framework 3.2.0
\ \  \\\  \  \ \  \\\  \  \ \  \\ \  \  \|___ \  \_|     
 \ \   __  \  \ \  \\\  \  \ \  \\ \  \      \ \  \      Listening: 0.0.0.0:8080
  \ \  \ \  \  \ \  \\\  \  \ \  \\ \  \      \ \  \     TLS: Disabled
   \ \__\ \__\  \ \_______\  \ \__\\ \__\      \ \__\    
    \|__|\|__|   \|_______|   \|__| \|__|       \|__|    https://www.huntframework.com


Try to browse http://0.0.0.0:8080
$ 
```
If I try tu debug application (gdb):
```
(gdb) run
Starting program: /home/antonio/Devel/dlang/myproject2/hunt-skeleton 
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7ffff7fca700 (LWP 14083)]
[New Thread 0x7ffff7fc3700 (LWP 14084)]
[New Thread 0x7ffff7fbc700 (LWP 14085)]
[New Thread 0x7ffff7fb5700 (LWP 14086)]
[New Thread 0x7ffff7fae700 (LWP 14087)]
[New Thread 0x7ffff7698700 (LWP 14088)]
[New Thread 0x7ffff7691700 (LWP 14089)]
[New Thread 0x7ffff716a700 (LWP 14090)]

Thread 9 "hunt-skeleton" received signal SIGUSR1, User defined signal 1.
[Switching to Thread 0x7ffff716a700 (LWP 14090)]
0x00007ffff779b361 in __GI___clock_nanosleep (clock_id=clock_id@entry=0, 
    flags=flags@entry=0, req=0x7ffff71688b0, rem=0x7ffff71688c8)
    at ../sysdeps/unix/sysv/linux/clock_nanosleep.c:48
48	../sysdeps/unix/sysv/linux/clock_nanosleep.c: No such file or directory.
(gdb) 
```

My system:
Ubuntu 20.04.1 LTS
DMD64 D Compiler v2.090.1
DUB version 1.19.0

**Comment by ddcovery** [comment]
After rebooting my machine it seems to work properly...

**Comment by zoujiaqing** [comment]
OK;)

**Comment by ddcovery** [comment]
Sorry zoujiaqing :-)
After reboot, it begun to fail

First time I ran the program result was this:

![Screenshot from 2020-08-02 19-46-53](https://user-images.githubusercontent.com/6564217/89129159-5cfa2a80-d4fb-11ea-89d4-35cc498165d3.png)

Other runs doen't show the warning, but application stop after few requests.

If I run it with dub (dub run -v) then I obtain (after some requests)
![Screenshot from 2020-08-02 20-06-00](https://user-images.githubusercontent.com/6564217/89129192-a185c600-d4fb-11ea-9dab-1909306228fa.png)

**Comment by Heromyth** [comment]
It seems so strange.  The Hunt Framework 3.3 is comming and will be release soon. 
Then you can have an another test.

**Comment by ddcovery** [comment]
Fails with 3.3.0-rc.2 too.  I will wait for 3.3

**Comment by ddcovery** [comment]
which linux distribution are you using to run/test hunt-framework?

**Comment by zoujiaqing** [comment]
Please use 3.3.0 release version.

**Comment by ddcovery** [comment]
Same problem:

![Peek 2020-08-07 00-22](https://user-images.githubusercontent.com/6564217/89588637-5560bb80-d844-11ea-82be-21fdfdf3ac41.gif)

**Comment by Heromyth** [comment]
Can you use gdb to debug it? It's really difficult to reproduce this problem in our environment.

**Comment by ddcovery** [comment]
Sorry Heromyhth,
I really don't know how:  running on gdb there is a lot of errors about "Unable to open 'clock_nanossleep.c', "Unable to open 'epoll_wait.c', unnable to open 'futex-internal.h'... 
and software is switching to a new thread each time I "continue".
When running with VSCode, I can't run to cursor.
Sorry, but I'm not experienced enougth.

**Comment by Heromyth** [comment]
Create a file nambed `.gdbinit` in your `Home` directory:
```conf
set verbose off
handle SIGPIPE nostop noprint
handle SIGUSR1 nostop noprint
handle SIGUSR2 nostop noprint
```
which can ignore most of the warnings.

You can install the C++ extension for VS code.
![20200811091555](https://user-images.githubusercontent.com/1275109/89846304-6b0f1180-dbb3-11ea-9ec8-bccebbe63623.png)

And check the debug box in `settings` to allow breakpoints everywhere:
![20200811091904](https://user-images.githubusercontent.com/1275109/89846448-dd7ff180-dbb3-11ea-8223-9676b253d0aa.png)

Then you can debug the application.

More about this, see https://forums.dlangchina.com/thread/10057.

**Comment by ddcovery** [comment]
Thank you Heromyth.

I was able to configure and place breakpoints...  the main problem is the debug errors shown as popups by vscode about missing glibc files.

> "Unable to open 'clock_nanosleep.c': Unable to read file '/build/glibc-YYA7BZ/glibc-2.31/sysdeps/unix/sysv/linux/clock_nanosleep.c' (Error: Unable to resolve non-existing file '/build/glibc-YYA7BZ/glibc-2.31/sysdeps/unix/sysv/linux/clock_nanosleep.c')."

**Comment by ddcovery** [comment]
Finally, I tried with gdbgui  (it works nicely without this annoying popups).

The error that stops application is this:

```
Thread 
11 "hunt-skeleton" received signal SIGPIPE, Broken pipe.
[Switching to Thread 0x7ffff57b6700 (LWP 6678)]
__libc_write (nbytes=1265, buf=0x7ffff70e9000, fd=20) at ../sysdeps/unix/sysv/linux/write.c:26
26  ../sysdeps/unix/sysv/linux/write.c: No such file or directory.
```
And finally 

```
Program terminated with signal 
SIGPIPE, Broken pipe.
The program no longer exists.
```

As I  understand, doing repeatedly CTRL+F5 on Firefox causes it to abandon previous sockets before server writes the responses.  This causes the broken pipe signal on server when it tries to write the response.

I suppose you must manage manually the error if necessary and ignore the SIGPIPE on POSIX systems.

**Comment by Heromyth** [comment]
Do you have another OS? Can you test this problem in it?
Maybe the bad network communication  can cause some problem. In my environment, there is no any problem even I press CTRL+F5 quickly.

By the way, you can test the network with the other Hunt libraries like [Hunt](https://github.com/huntlabs/hunt), [Hunt-Http](https://github.com/huntlabs/hunt-http). All of them have an folder named `examples` where you can run some tests.

**Comment by ddcovery** [comment]
Do you refer a non POSIX OS?
Which OS do you primary use to develop and test hunt-framework?

**Comment by Heromyth** [comment]
Debian, Linux Mint (Ubuntu), Windows 10 etc.
X64 plantform.

**Comment by ddcovery** [comment]
I added the code to ignore the SIGPIPE signal (only valid on POSIX systems) on main.d

```d

import hunt.framework;
version(Posix)
{
    import core.sys.posix.signal;
}

void main(string[] args)
{
  version(Posix){
    sigset_t sigset;
    sigemptyset(&sigset);
    sigaction_t siginfo;
    siginfo.sa_mask = sigset;
    siginfo.sa_flags = SA_RESTART;
    siginfo.sa_handler = SIG_IGN;
    sigaction(SIGPIPE, &siginfo, null);
  }
  app().run(args);

}
```

With this change, the application works without interruption when a pipe brokes (i.e.: Firefox discarding a socket before a response is written by the server).

Once in a while, a warning is shown in console:

> 2020-Aug-30 02:41:28.8044936 | 9613 | warning | AbstractStream.tryRead | warning on read: fd=20, errno=11, message=Resource temporarily unavailable | ../../../.dub/packages/hunt-1.6.1/hunt/source/hunt/io/channel/posix/AbstractStream.d:123

As I mentioned in a previous comment, it seems that hunt is not managing  SIGPIPE properly.

**Comment by Heromyth** [comment]
It seems that we need to do more searches about `SIGPIPE, Broken pipe.` and to find a way to fix this.

**Comment by Heromyth** [comment]
It seems that we need to do more searches about `SIGPIPE, Broken pipe.` and to find a way to fix this.

**Comment by Heromyth** [comment]
It seems that we need to do more searches about `SIGPIPE, Broken pipe.` and to find a way to fix this.

**Comment by Heromyth** [comment]
It seems that we need to do more searches about `SIGPIPE, Broken pipe.` and to find a way to fix this.

**Comment by Heromyth** [comment]
It seems that we need to do more searches about `SIGPIPE, Broken pipe.` and to find a way to fix this.

**Comment by Heromyth** [comment]
It seems that we need to do more searches about `SIGPIPE, Broken pipe.` and to find a way to fix this.

**Comment by Heromyth** [comment]
It's really difficult to reproduce this problem. 
Maybe my GDB and OS are all the latest.  When debugging a application, there are no any signals received.
However, I still added your code to ignore the SIGPIPE signal in commit https://github.com/huntlabs/hunt-net/commit/8494ac88fdf3c45e1aee67fb3546d1dba3448d2b.
