### ISSUE TITLE
Documentation

### ISSUE THREAD

**Issue by 89z** [huntlabs/hunt-framework#171]
Seems to be missing:

https://www.huntlabs.net/docs/hunt-framework-current/begin

**Comment by Heromyth** [comment]
Check [here](https://github.com/huntlabs/hunt-framework-docs), please.

**Comment by 89z** [comment]
Please reopen - I dont see any documentation on this API:

https://github.com/huntlabs/hunt-framework/blob/master/source/hunt/framework/util/Url.d

**Comment by Heromyth** [comment]
The documentation is about how to use the Hunt Framework, not for the API.
It's so sorry that there is no documentation avaliable for the API by now.

**Comment by 89z** [comment]
Yes it is - I found it here:

http://hunt-framework.dpldocs.info/hunt.framework.util.Url.html

**Comment by Heromyth** [comment]
It's out of date. It may be a long time before the API documents get updated again.

**Comment by Heromyth** [comment]
If you want to use URL, you can use [HttpURI](https://github.com/huntlabs/hunt-net/blob/master/source/hunt/net/util/HttpURI.d).
[Here](https://github.com/huntlabs/hunt-net/blob/master/examples/UnitTest/source/test/HttpUriTest.d) are some tests for it.

**Comment by 89z** [comment]
I cleared the cache, check again:

http://hunt-framework.dpldocs.info/hunt.framework.util.Url.html

**Comment by Heromyth** [comment]
It's nice. We will try our best to add more comments in the source code.
By the way, how can I update the content to the latest?

**Comment by 89z** [comment]
at the very bottom, click "Clear Cache"

but dont do it too much

**Comment by Heromyth** [comment]
Oh, thanks. The link is added [here](https://github.com/huntlabs/hunt-framework-docs/blob/master/README.md).

**Comment by 89z** [comment]
Thank you!
