### ISSUE TITLE
Hunt vs Vibed

### ISSUE THREAD

**Issue by bubnenkoff** [huntlabs/hunt-framework#39]
What is the design/philosophy difference between Hunt and Vibed?

**Comment by donglei** [comment]
Hi, thanks for your attention about hunt.
We are working on the official website for [hunt](http://collied.org/), the design/philosophy will show there.

**Comment by bubnenkoff** [comment]
Hope that it will be based on Hunt :)

2016-05-23 10:30 GMT+03:00 donglei notifications@github.com:

**Comment by donglei** [comment]
It is necessary.

**Comment by zoujiaqing** [comment]
@bubnenkoff , vibe.d is a library, but hunt is a framework.

**Comment by bubnenkoff** [comment]
Explain plz. What simmilar what difference

**Comment by zoujiaqing** [comment]
I don't know about vibed.
Hunt framework like ruby's rails, python's django, java's play framework, php's laravel.

**Comment by denizzzka** [comment]
Why hunt isn't uses vibe.d?

**Comment by zoujiaqing** [comment]
Hello @denizzzka ,

Before we have a flexible and efficient event driven library, it is [collie.](https://github.com/putaolabs/collie/)

Collie with reference to the netty design ideas, flexible use and expansion, this point Java developers are very much in favor of.

Collie itself supports the realization of the HTTP protocol, so we build the hunt framework based on collie.

Like [netty](http://netty.io/) and [play framework](https://playframework.com/).

**Comment by bubnenkoff** [comment]
I think it's time to add at last small comparison with vibed to readme. 
I plan to write mention about hunt on some news sites, and visitors would interesting to read about it's futures on readme.

**Comment by sathanu** [comment]
I have create a sample web app using hunt framework. It is simple and easy to develop.
I have struggled with 
1. How to create rest api(return json / xml based on the request)
2. How to deploy web server (XAMPP, Apache)

**Comment by zoujiaqing** [comment]
1. response json object
```D
class IndexController : Controller
{
    mixin MakeController

    @Action
    void test()
    {
        JSONValue json = [ "language": "D" ];
        this.response.json(json);
    }
}
```

2. use nginx & apache proxy your hunt application

nginx:
```conf
http {
    server {
            server_name yourdomain.com;

            root /data/www/huntapplication/public;

            location / {
                    proxy_pass http://yourdoman.com:8080;
            }
    }
}
```

apache:
```conf
<VirtualHost *>
    ServerName yourdomain.com
    ProxyPass / http://localhost:8080/
    ProxyPassReverse / http://localhost:8080/
</VirtualHost>
```

**Comment by zoujiaqing** [comment]
@bubnenkoff you can try hunt 1.0 :)

**Comment by dejlek** [comment]
Having something like Play in the D world is remarkable... If that is your goal you will have lots of followers. :)
