### ISSUE TITLE
0.4.0 is not buildable

### ISSUE THREAD

**Issue by bubnenkoff** [huntlabs/hunt-framework#50]
I mean: hunt/examples/website/

You did release too early, 0.4.0 is not even buildable:

....\source\hunt\view\package.d(93,28): Error: file "layouts/main.dhtml" cannot
 be found or not in a path specified with -J
....\source\hunt\view\templerender.d(24,13): Error: template instance hunt.view
.compile_temple_file!("layouts/main.dhtml", void) error instantiating
source\app\controller\index.d(51,12):        instantiated from here: setLayout!"
layouts/main.dhtml"
Compiling content.dhtml...
context parsing..............................................
delim check........................
dmd failed with exit code 1.

Please do release only after testing. Or people will think about Hunt how about low quality project.

**Comment by denizzzka** [comment]
I am actively use Travis-CI for automatic testing builds after pushing new commits. Helps a lot!

**Comment by dushibaiyu** [comment]
@bubnenkoff  whitch folder is main.dhtml in?
in hunt/examples/website/:
the dhtml must in hunt/examples/website/resources/views/.
it is config in dub.json. in this config: "stringImportPaths": [ "./resources/views" ],

**Comment by bubnenkoff** [comment]
@dushibaiyu dushibaiyu yeah I talk about hunt/examples/website/
is it's buildable for you?

**Comment by dushibaiyu** [comment]
@denizzzka  Thanks . i will add

**Comment by dushibaiyu** [comment]
@bubnenkoff it is buildable for me. I am in Linux X64. and Run is also ok.
dub test is faild.

**Comment by bubnenkoff** [comment]
@dushibaiyu I am Windows user. 
I really hope to success of your project! It's look like really cool! But need a little bit more polish)

**Comment by dushibaiyu** [comment]
@bubnenkoff  I will test on windows.

**Comment by dushibaiyu** [comment]
@bubnenkoff  Now master fix build and run.

**Comment by dushibaiyu** [comment]
We test in win7-32bit and win10-64bit.

**Comment by bubnenkoff** [comment]
I think you should do some point release like 0.4.0.1 because it's fix important issue
Only please do not do major point release like 0.4.1 or versy woon we will get "Hunt v.100"

**Comment by donglei** [comment]
hunt/examples/website/ can build and run ok.

**Comment by bubnenkoff** [comment]
@donglei  Still can't run https://snag.gy/WeY7Ns.jpg
0.0.0.0:8080 also do not working
