### ISSUE TITLE
The session ID is not safe

### ISSUE THREAD

**Issue by cym13** [huntlabs/hunt-framework#51]
The problem
===========

The way the session ID as generated is unsafe :

    public string generateSessionId()
    {
        import std.digest.sha;
        import std.format;
        import std.datetime;
        import std.random;
        import core.cpuid;
        import std.string;

        auto str = toHexString(sha1Of(format("%s--%s--%s",
            Clock.currTime().toISOExtString, uniform(long.min, long.max), processor())));

        return toLower(cast(string)(str[]));
    }

This showcases many cryptographic issues:

- the current time isn't random at all and is easy to predict with a low error margin.

- uniform isn't a cryptographically secured pseudo random number generator, given enough data (a few hundreds of session ids, nothing difficult to generate) it's easy to predict any further input.

- the processor is not random either, it's possible to find it and once leaked it is very hard to change

- sha1 is completely unsafe and should never be used. There is no good reason to use it today instead of sha256, sha512 or blake2.

The solution
============

A session id should be unique and cryptographically secure. Unfortunately D
doesn't currently provide a standard CSPRNG. I would recommend to take the
sha256 of 64 bytes of your systems random number generator source :

- /dev/urandom   on Linux/MAC
- CryptGenRandom on Windows

If your system doesn't provide one of those refuse to compile! It's important
not to silently induce a fake sense of security.

**Comment by vegax87** [comment]
Blake2 is the best option for hashing, I hope that some devs will have time to port it on D language

**Comment by bubnenkoff** [comment]
Maybe it's bertter to create JWT auth by default?

**Comment by cym13** [comment]
@vegax87: It is, at least performance-wise. However I would hardly see it not being ported to D a blocking point: I doubt the performance increase justifies not using sha256 if that's what's readily available.

**Comment by cym13** [comment]
@bubnenkoff: I have no strong opinion on that besides the fact that JWT add a lot of complexity.

**Comment by cym13** [comment]
Correction: I don't know what I was thinking writting that I recommend taking « 64 bytes from the CSPRNG », that's quite enormous. Taking 128 bits is enough for reasonnable guarantees of non-collision as that's what's used by type 4 UUIDs as defined in RFC4122.

**Comment by vegax87** [comment]
Technically sha1Of is not the only available alias: https://dlang.org/phobos/std_digest_sha.html

ubyte[20] hash = sha1Of("abc");
assert(hash == digest!SHA1("abc"));

ubyte[28] hash224 = sha224Of("abc");
assert(hash224 == digest!SHA224("abc"));

ubyte[32] hash256 = sha256Of("abc");
assert(hash256 == digest!SHA256("abc"));

ubyte[48] hash384 = sha384Of("abc");
assert(hash384 == digest!SHA384("abc"));

ubyte[64] hash512 = sha512Of("abc");
assert(hash512 == digest!SHA512("abc"));

ubyte[28] hash512_224 = sha512_224Of("abc");
assert(hash512_224 == digest!SHA512_224("abc"));

ubyte[32] hash512_256 = sha512_256Of("abc");
assert(hash512_256 == digest!SHA512_256("abc"));

**Comment by cym13** [comment]
@vegax87 Yep, all the more reason to walk away from it.

**Comment by dushibaiyu** [comment]
Thanks all. 
THe hunt will be reconsitution。 when the new collie(https://github.com/huntlabs/collie/tree/http) is test to stable.
and it fix, I tink use the uuid will better.

**Comment by cym13** [comment]
@dushibaiyu Note that you can't use std.uuid here though because it doesn't use a CSPRNG. You need to read directly from the system's CSPRNG. Vibe.d provides a good example: 

https://github.com/rejectedsoftware/vibe.d/blob/master/crypto/vibe/crypto/cryptorand.d

**Comment by vegax87** [comment]
@cym13 I found this library: https://github.com/LightBender/SecureD that  provides:

```
HASH: SHA2-384
HMAC: SHA2-384
KDF: PBKDF2 (HMAC/SHA2-384)
AEAD Symmetric: AES-256-CTR-HMAC384
Asymmetric: ECC-P384 (Key Derivation + Sign/Verify with SHA2-384)
**RNG: System RNG on POSIX and Windows**
**OTHER: Constant Time Equality**
```

**Comment by shove70** [comment]
auto str = toHexString(sha1Of(format("%s--%s--%s",
        Clock.currTime().toISOExtString, uniform(long.min, long.max), processor())));

The new version has not yet been updated. The risk of conflict is relatively high.

**Comment by viile** [comment]
fix it already in our plan, we will  fix it in the next version.
