### ISSUE TITLE
Possible cache corruption

### ISSUE THREAD

**Issue by cym13** [huntlabs/hunt-framework#52]
Hi,

The way the function getByKey in mapCache is implemented right know is not safe:

    override string getByKey(string master_key,string key, lazy string v= string.init)
    {
        string pk = master_key ~ key;
        _mutex.reader.lock();
        scope(exit) _mutex.reader.unlock();
        return _map.get(pk,v);
    }

By just concatenating the keys it is possible to access other access other keys by mistake:

    getByKey("AA", "B") == getByKey("A", "AB");

For example this can have security consequences if the key is taken from user input even without any access to the master key part.

Outside of any context the best way to concatenate them I can think of is:

    override string getByKey(string master_key, string key, lazy string v=string.init)
    {
        string prefix = master_key.length.to!string ~ ",";
        string pk = prefix ~ master_key ~ key;
        _mutex.reader.lock();
        scope(exit) _mutex.reader.unlock();
        return _map.get(pk,v);
    }

It works by making the length of the master key explicit. I use a non-numerical separator to remove ambiguity in case the master_key starts with a number. Of course the setByKey function must be adapted too. That way it is not possible to be ambiguous :

    getByKey("AA", "B") -> 2,AAB
    getByKey("A", "AB") -> 1,AAB

Note that in most cases you don't have to unserialize that key, the setByKey just builds its key the same way, it doesn't have to check existing the formatting of existing keys.

**Comment by dushibaiyu** [comment]
Thanks.
it will fixed.
