### ISSUE TITLE
Fail to dub run hunt-skeleton 

### ISSUE THREAD

**Issue by shawnye** [huntlabs/hunt-framework#55]
git clone https://github.com/putaolabs/hunt-skeleton.git myproject

but fail to dub run the executable for two reasons:

1. It needs `logs` directory, I can make it manually.
2. I have change `http.port = 8083` in `config/application.conf`, but it still remains 8080 

<pre>
g:\dev\d\myproject>dub run --force
Performing "debug" build using dmd for x86.
collie 0.9.2: building configuration "default"...
use CustomTimer!!!!
hunt 0.5.1: building configuration "default"...
use CustomTimer!!!!
context parsing..............................................
delim check........................
hunt-skeleton ~master: building configuration "application"...
use CustomTimer!!!!
Linking...
Running .\hunt-skeleton.exe
2017-02-10T14:45:15.187:C:\Users\Administrator\AppData\Roaming\dub\packages\hunt-0.5.1\hunt\source\h
unt\application\controller.d:addRouteList:211 addRouteList : app.controller.index.IndexController.in
dex

std.socket.SocketOSException@std\socket.d(2723): Unable to bind socket: 以一种访问权限不允许的方式做了一个访问套接字的尝试。
----------------
0x004CC050 in @trusted void std.socket.Socket.bind(std.socket.Address)
...
**Because 8080 has been occupied**
</pre>

**Comment by zoujiaqing** [comment]
Your computer's 80 port has been used by other application.

This configuration option is currently invalid, the next version we will fix it.
