### ISSUE TITLE
问个数据库的问题

### ISSUE THREAD

**Issue by huangyy** [huntlabs/hunt-framework#57]
问一下，如果数据库改成mysql，是不是
database.default.driver=mysql
这么写就可以了？database.default.url格式照旧？

**Comment by zoujiaqing** [comment]
其实这个我们考虑过去掉 database.default.driver 配置，只保留 database.default.url 这项配置，这几天会有一个最终的明确再说，请稍等 :)

**Comment by huangyy** [comment]
还有，0.6版本，是不是不支持redis了？我看0.6的配置文件里面，只有memcache了。另外，IO和thread有什么区别？0.6版本只有thread，没有IO了，这个参数是不是就是fork线程的数量？每个线程都是异步的？

**Comment by zoujiaqing** [comment]
@huangyy 请参照 hunt 主分支的 examples/entity/ 的使用示例。
