### ISSUE TITLE
hunt 0.6.0 版本问题

### ISSUE THREAD

**Issue by RemoteEvilDragon** [huntlabs/hunt-framework#58]
使用hunt 0.6.0 版本结合 dub build 命令编译，出现如下问题

## Warning for package libasync, configuration 32mscoff ##

The following compiler flags have been specified in the package description
file. They are handled by DUB and direct use in packages is discouraged.
Alternatively, you can set the DFLAGS environment variable to pass custom flags
to the compiler, or use one of the suggestions below:

-m32mscoff: Use --arch=x86/--arch=x86_64/--arch=x86_mscoff to specify the target architecture

## Warning for package libasync, configuration 32mscoff ##

The following compiler flags have been specified in the package description
file. They are handled by DUB and direct use in packages is discouraged.
Alternatively, you can set the DFLAGS environment variable to pass custom flags
to the compiler, or use one of the suggestions below:

-m32mscoff: Use --arch=x86/--arch=x86_64/--arch=x86_mscoff to specify the target architecture

Performing "debug" build using dmd for x86_64.
collie 0.9.2: building configuration "default"...
derelict-util 2.0.6: building configuration "library"...
derelict-pq 2.0.3: building configuration "library"...
vibe-d:utils 0.7.30: building configuration "library"...
vibe-d:data 0.7.30: building configuration "library"...
vibe-d:core 0.7.30: building configuration "libevent"...
mysql-native 1.0.0: building configuration "library"...
ddbc 0.3.2: building configuration "full"...
../../../../.dub/packages/ddbc-0.3.2/ddbc/source/ddbc/drivers/mysqlddbc.d(319,15): Error: undefined identifier 'Command'
../../../../.dub/packages/ddbc-0.3.2/ddbc/source/ddbc/drivers/mysqlddbc.d(342,23): Error: undefined identifier 'FieldDescription'
../../../../.dub/packages/ddbc-0.3.2/ddbc/source/ddbc/drivers/mysqlddbc.d(359,23): Error: undefined identifier 'ParamDescription'
dmd failed with exit code 1

**Comment by zoujiaqing** [comment]
@RemoteEvilDragon 这个是ddbc 依赖的 mysql 驱动版本问题，我们已经给他们提交了补丁代码，但是他们还没有合并进去。

手动修改，使用老版本的 mysql native 驱动是可以的。

**Comment by RemoteEvilDragon** [comment]
👌
