### ISSUE TITLE
vue.js for frontend

### ISSUE THREAD

**Issue by bubnenkoff** [huntlabs/hunt-framework#61]
You should look at http://vuejs.org/ for client side. It's much better and modern then ReactJS.

**Comment by zoujiaqing** [comment]
I know vue, my team use vue in other product.

You want hunt use javascript to render pages?

**Comment by bubnenkoff** [comment]
I think that in 90% it's only right way. Because web moving to webapps
instead of classical static sites


вс, 16 апр. 2017 г. в 10:20, Brian Zou <notifications@github.com>:
