### ISSUE TITLE
When remove a cookie, there is a user experience problem.

### ISSUE THREAD

**Issue by shove70** [huntlabs/hunt-framework#64]
remove a cookie:

`response.setCookie("username", "", -1);`

When the second parameter “value” is passed into a blank string “”, a assert error is encountered.
While removing the cookie need to pass a specific value, is unreasonable.

## Recommendation

cookie.d  line 361:

```
    void set(string name, string value)
    in
    {
        assert(name != null);
        //assert(value != null);      // Comment it, or: Comment on it, or: rewrite the assert statement based on the value of the expires variable
    }
```

## Thanks for providing such a powerful Hunt.

**Comment by viile** [comment]
yes,you're right
thanks
welcome to submit your updated
