### ISSUE TITLE
SessionId persistence bug.

### ISSUE THREAD

**Issue by shove70** [huntlabs/hunt-framework#65]
SessionInterface session = request.getSession();

When we use session, we get a different sessionId for each new request on the own client. Access to all the source code of hunt, found that: according to the designer's intent is to use the setCookie("hunt_session", sessionId) to save the sessionId, and the source code is not setCookie("hunt_session", ...) this code should be careful not to miss.

# Solution

at line: 138, in request.d:
```
	SessionInterface getSession( S = Session)(string sessionName = "hunt_session", SessionStorageInterface t =  newStorage()) //if()
	{
		auto co = getCookie(sessionName);
		if (co is null) return new S(t);
		return new S(co.value, t);
	}
```
Replace this method as：
```
	SessionInterface getSession( S = Session)(string sessionName = "hunt_session", SessionStorageInterface t =  newStorage()) //if()
	{
		auto cookie = getCookie(sessionName);
		if (cookie is null)
		{
			S session = new S(t);
			string sessionId = session.getId();
			this.createResponse().setCookie(sessionName, sessionId);	// In fact, this sentence is added, the sessionId will be saved to the cookie
		
			return session;
		}
	
		return new S(cookie.value, t);
	}
```

**Comment by viile** [comment]
thanks, you can open a new pull request . i'll merge your code

**Comment by shove70** [comment]
OK. thanks.
