### ISSUE TITLE
I would like to ask, how to write static resources in the routing

### ISSUE THREAD

**Issue by shove70** [huntlabs/hunt-framework#72]
such as：GET		/public/*					staticDir:resources

**Comment by viile** [comment]
in actual fact,we use nginx to process static resources,so this feature is not supported at this time

**Comment by zoujiaqing** [comment]
You can use this route and create an Action:
```bash
GET    /public/<filename:.*>    core.staticfile
```

in this Action read file & output.

**Comment by shove70** [comment]
No, in the hunt source does not see this feature support, core.staticfile Action code does not exist. I have finished writing this feature and just submitted a pull request that is waiting for the merge code.
```

GET                        /public                                staticDir:public

```

**Comment by shove70** [comment]
@zoujiaqing, I know, thanks
