### ISSUE TITLE
建议添加isAsync To Controller

### ISSUE THREAD

**Issue by dushibaiyu** [huntlabs/hunt-framework#81]
可以添加一个 bool isAsync() 函数到Controller类，默认是return true。
允许自己定义成return false。 
如果return false。 就可以在handler处理完逻辑GC.free 掉 Controller。 
以便优化GC暂停频率和时间。

**Comment by dushibaiyu** [comment]
First, remember, Midori was an entire OS written to use garbage collected memory. We learned some key lessons that were necessary for this to perform adequately. But I’d say the prime directive was to avoid superfluous allocations like the plague. Even short-lived ones. There is a mantra that permeated .NET in the early days: Gen0 collections are free. Unfortunately, this shaped a lot of .NET’s library code, and is utter hogwash. Gen0 collections introduce pauses, dirty the cache, and introduce beat frequency issues in a highly concurrent system.

首先，大家是否还记得曾经的Midori项目。Midori要实现的是一个完整的操作系统，有效地使用垃圾回收所得到的内存。从该项目中，我们学到了适当运作此类项目的关键经验教训。我要强调的一点，应该像避免瘟疫一样避免夸大的内存分配，即使是短生命的内存分配。早期在.NET领域有一个广泛传播的口头禅：“Gen0集合是无价的”。不幸的是，这句话影响了很多的.NET库代码，完全驴头不对马嘴。Gen0集合导致了暂时性中断、弄脏的缓存，并在高度并发系统中引入了高频问题。
http://joeduffyblog.com/2015/11/19/asynchronous-everything/
对于CLR 这种分3代的 GC。 第一代优化这么好，还存在的问题。

**Comment by viile** [comment]
This feature has been supported
