### ISSUE TITLE
There was a problem with the last submission.

### ISSUE THREAD

**Issue by shove70** [huntlabs/hunt-framework#82]
There was a problem with the last submission：

session.d:
	void setExpire(int expire)
	{
		this._expire = expire;
		this._cacheDriver.setExpire(expire);		<-- here
	}
	
file.d: (class FileCache)

    override void setExpire(int expire)
    {
        this._expire = expire;		<-- here
    }
	
Cause app.start() not run.

**Comment by viile** [comment]
what's problem about sesion  expire?

you should use app.run() to start your application

**Comment by shove70** [comment]
You modified the design of session storage yesterday and today, but there are problems, the problem is that I posted it here. When you create a new blank project and dependent on the last hunt Version (not 0.7.1 release), you will find that the server does not start listening at all.

**Comment by viile** [comment]
I did as you told me, but can't recreate this problem.
maybe you can try delete 'dub.selections.json' and pull the latest hunt  and rebuild your code
If it still doesn't work , please submit error log   and show me your code. i'll fix it

**Comment by shove70** [comment]
I see, when the configuration file application.conf does not set session.storage, hunt does not give it a default value.
```

session.storage = 
session.prefix = huntsession_
session.expire = 3600
```

modify:

session.d:

```
class Session
{
	this(string driver = "memory")
	{
		if (driver == string.init)
		{
			driver = "memory";       // add this.
		}
		
		this._driverName = driver;
		switch(driver)
		{
```

I have submitted the code, please merge, thank you.

**Comment by viile** [comment]
thanks , I've fixed it
