### ISSUE TITLE
Rest API and Deploy into web server

### ISSUE THREAD

**Issue by sathanu** [huntlabs/hunt-framework#90]
I have create a sample web app using hunt framework. It is simple and easy to develop.
I have struggled with

How to create rest api(return json / xml based on the request)
How to deploy into web server (XAMPP, Apache)

**Comment by zoujiaqing** [comment]
Hi @sathanu

1. response json object in Controller class
```D
class IndexController : Controller
{
    mixin MakeController

    @Action
    void test()
    {
        JSONValue json = [ "language": "D" ];
        this.response.json(json);
    }
}
```

2. use nginx & apache proxy your hunt application

nginx:
```conf
http {
    server {
            server_name yourdomain.com;

            root /data/www/huntapplication/public;

            location / {
                    proxy_pass http://yourdoman.com:8080;
            }
    }
}
```

apache:
```conf
<VirtualHost *>
    ServerName yourdomain.com
    ProxyPass / http://localhost:8080/
    ProxyPassReverse / http://localhost:8080/
</VirtualHost>
```

**Comment by zoujiaqing** [comment]
@sathanu Now hunt don't need depend other proxy to access static files.
You can try it!
