### ISSUE TITLE
Controller's Action can return string / int / JSONValue

### ISSUE THREAD

**Issue by zoujiaqing** [huntlabs/hunt-framework#91]
```D
import hunt;

class IndexController : Controller
{
	mixin MakeController;

	@Action
	string helloworld()
	{
		return "hello world!";
	}

	@Action
	int hello123()
	{
		return 123;
	}

	@Action
	JSONValue hellojson()
	{
		JSONValue j = [ "hello": "json" ];

		return j;
	}

	@Action
	Reponse hello()
	{
		response.setContent("hello");

		return response;
	}
}
```

**Comment by Heromyth** [comment]
A unified return type will make the controller's api more extendable. Maybe, we can use a interface called IActionResult for this like what the ASP.Net Core does.

See also:
https://docs.microsoft.com/zh-cn/aspnet/core/web-api/action-return-types?view=aspnetcore-2.0

**Comment by zoujiaqing** [comment]
The current version is more suitable for this format.
