### ISSUE TITLE
Please add a link from readme to the Wiki

### ISSUE THREAD

**Issue by EmTee70** [huntlabs/hunt-framework#98]
Many projects don't have a Wiki, so that at first I missed it, when reading only the readme and installing your skeleton example.

And than please place a view into the skeleton, it is not mentioned where to store the view.
And translate the complete wiki to English :-)

**Comment by zoujiaqing** [comment]
OK!

I'm go to add more sample code to skeleton.

**Comment by zoujiaqing** [comment]
@EmTee70 You can see hunt-skeleton project, sample code for views is added.
