### ISSUE TITLE
Have you thought about a scaffolding scirpt

### ISSUE THREAD

**Issue by EmTee70** [huntlabs/hunt-framework#99]
For getting started with a certain db-table I like the rails scaffolding  a lot.

I thought it would be quite cool to export an mysqldump of the table definition and read this
information to get the definitions needed for the ORM mapping.
Unfortunately my D skills are still very small, but in theory it should be possible to do this at 
compiletime? Producing the needed string mixins.

If you could offer something like this I think Hunt would be far more attractive to give it a try.

**Comment by zoujiaqing** [comment]
Yes, D can do it.
But, we need code hiting.

Let't me think.
Can create a tool from mysqldump file convert to Entity files.

Thanks for your suggestion : )
